messages:
  check_on_player: '§7[§b§l!§7] §fКоманду может использовать только от лица игрока'
  payment_successful: '§5§l[§d§lФЕРМА§5§l] §fПеревод успешно выполнен'
  timer_start: '§5§l[§d§lФЕРМА§5§l] §fВыращивание щитков запущено'
  error_timer_enabled: '§7[§b§l!§7] §fУ вас уже запущен процесс выращивания щитков'
  error_timer_enabled_2: '§7[§b§l!§7] §fУ вас недостаточно щитков, необходимо 5'
  timer_start_2: '§5§l[§d§lФЕРМА§5§l] §fВыращивание ракушек запущено'
  error_timer_enabled_3: '§7[§b§l!§7] §fУ вас уже запущен процесс выращивания ракушек'
  error_timer_enabled_4: '§7[§b§l!§7] §fУ вас недостаточно ракушек, необходимо 5'

timer:
  scute: '7200' # Время выращивания в секундах для 'щитков'
  nautilus_shell: '10800' # Время выращивания в секундах для 'ракушек'

prices:
  scute: '5000' # Награда за выращивание 'щитков'
  nautilus_shell: '10000' # Награда за выращивание 'ракушек'

gui: # Заголовок меню
  ferma_title: 'Ферма'

book: # Редактирование предмета 'Книга'
  title: 'Информация'
  lines:
    - 'Строка 1'
    - 'Строка 2'
    - 'Строка 3'

scute: # Редактирование предмета 'Щиток'
  title: 'Панцирь'
  lines:
    - 'Строка 1'
    - 'Строка 2'
    - 'Строка 3'

nautilus_shell: # Редактирование предмета 'Раковина наутилуса'
  title: 'Ракушка'
  lines:
    - 'Строка 1'
    - 'Строка 2'
    - 'Строка 3'

flower_pot: # Редактирование предмета 'Цветочный горшок от щитка'
  title: 'Нажми, что-бы вырастить щитки'
  lines:
    - 'Строка 1'
    - 'Строка 2'
    - 'Строка 3'
  timer_line: 'Осталось время: %time%' # Последняя строка заменится на этот текст. %time% - Оставшиеся время до выращивания
  reward_line: 'Нажмите, чтобы забрать деньги'

flower_pot_2: # Редактирование предмета 'Цветочный горшок от ракушки'
  title: 'Нажми, что-бы вырастить ракушку'
  lines:
    - 'Строка 1'
    - 'Строка 2'
    - 'Строка 3'
  timer_line: 'Осталось время: %time%' # Последняя строка заменится на этот текст. %time% - Оставшиеся время до выращивания
  reward_line: 'Нажмите, чтобы забрать деньги'

